# Generated by Django 4.0.1 on 2022-01-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='dni')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_company', models.BooleanField(default=False, help_text='If the client is a company, check true', verbose_name='is company')),
            ],
        ),
    ]
