# Generated by Django 4.0.1 on 2022-01-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='days')),
                ('payment_method', models.CharField(choices=[('CC', 'Credit Card'), ('CASH', 'Cash'), ('WT', 'Wire Transfer')], default='CASH', max_length=4, verbose_name='payment method')),
                ('state', models.CharField(choices=[('P', 'Pending'), ('P0', 'Paid Out'), ('D', 'Deleted')], default='P', max_length=2, verbose_name='state')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
